package com.ts.blog.kie

import com.ts.blog.rules.type.Category

/**
* TechSquids blog model declaration
* position annotation is optional
*/

declare Blog

   @author( Rahul )
   @dateOfCreation( 02-June-2018 )

   //Adding annotation to avoid infinite loop execution when any property is updated
   @propertyReactive
   topic : String
   subtopic:String
   likes : Integer
   time : java.util.Date
   visits : Integer
   category : Category
   rating : Integer
end